# Generated by Django 4.1.6 on 2023-02-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAP',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('order_id', models.IntegerField()),
                ('purchase_id', models.IntegerField()),
                ('csm_name', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('mac_addr', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
