# Generated by Django 4.1.6 on 2023-02-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_inventory', '0002_iap_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iap',
            old_name='mac_addr',
            new_name='macaddr',
        ),
    ]
